### ISSUE TITLE
Problems about multiview

### ISSUE THREAD

**Issue by menglk2012** [ch3cook-fdu/Vote2Cap-DETR#26]
When trained with use_multiview instead of using use_color, there are some problems listed below: 
----------
Traceback (most recent call last):
  File "main.py", line 337, in <module>
    main(args)
  File "main.py", line 315, in main
    do_train(
  File "/home/e723/mlk/Vote2Cap-DETR-master/engine.py", line 156, in do_train
    for batch_idx, batch_data_label in enumerate(dataloaders['train']):
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/e723/mlk/Vote2Cap-DETR-master/datasets/scene_scanrefer.py", line 341, in __getitem__
    self.multiview_data[pid] = h5py.File(
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/e723/anaconda3/envs/Vote2CapDETR/lib/python3.8/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = './data/scannet/scannet_data/enet_feats_maxpool.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
----------
It seems that I have not got the 'enet_feats_maxpool.hdf5' database. How to use Enet get it? Thanks!

**Comment by ch3cook-fdu** [comment]
Please refer to the instructions in step5 at https://github.com/daveredrum/Scan2Cap/tree/main?tab=readme-ov-file#data-preparation.
