### ISSUE TITLE
”cd third_party/pointnet2；python setup.py install“

### ISSUE THREAD

**Issue by cyb1219257828** [ch3cook-fdu/Vote2Cap-DETR#6]
An error occurred using this installation method. RuntimeError: Error compiling objects for extension

**Comment by ch3cook-fdu** [comment]
Please first make sure `gcc` and `g++` is successfully installed:

```
gcc -v
```

If you still cannot compile `pointnet2`, could you give me more details?

**Comment by cyb1219257828** [comment]
According to the prompt information, it seems that the installation method through setup.py has been deprecated. The specific error message has been sent to the email csjch3cook@gmail.com

**Comment by ch3cook-fdu** [comment]
It seems that torch is not properly installed
```
fatal error: cuda_runtime_api.h: No such file or directory compilation terminated.
```
Please try installing `torch-1.7.1-cu110` using the following command:

```
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by ch3cook-fdu** [comment]
https://github.com/erikwijmans/Pointnet2_PyTorch/issues/139

**Comment by cyb1219257828** [comment]
Thank you for your reply. This issue is indeed due to the issue with cuda-11.0 when I installed multiple versions of cuda.Now, when I execute step '4.1 MLE Training for 3D Dense Captioning', 'No such file or directory: './data/ScanRefer_filtered_train.json'' appears.

**Comment by ch3cook-fdu** [comment]
Please refer to the `Preparing Language Annotations.` step in [data preparation](https://github.com/ch3cook-fdu/Vote2Cap-DETR#2-dataset-preparation).

**Comment by cyb1219257828** [comment]
Thank you, the previous problem has been solved, and now it has been found in step 4.1 that the version number of the transformers package may be incorrect. You can send me the version number of all python packages.thank you.

发件人: Sijin Chen
发送时间: 2023年10月5日 22:23
收件人: ch3cook-fdu/Vote2Cap-DETR
抄送: Fourier; Author
主题: Re: [ch3cook-fdu/Vote2Cap-DETR] ”cd third_party/pointnet2；python setup.py install“ (Issue #6)

Please refer to the Preparing Language Annotations. step in data preparation.

**Comment by ch3cook-fdu** [comment]
Sure thing. However, I have been working on another project with this environment, thus the environment might be a bit messy. Here is the output of `pip list`


```{bash}
Package                  Version
------------------------ -----------
accelerate               0.20.3
annotated-types          0.5.0
appdirs                  1.4.4
bitsandbytes             0.41.1
blis                     0.7.10
catalogue                2.0.9
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.6
cmake                    3.26.4
confection               0.1.1
contourpy                1.1.0
cycler                   0.11.0
cymem                    2.0.7
Cython                   0.29.35
decorator                5.1.1
docker-pycreds           0.4.0
easydict                 1.10
filelock                 3.12.2
fonttools                4.42.0
fsspec                   2023.6.0
gitdb                    4.0.10
GitPython                3.1.32
h5py                     3.9.0
huggingface-hub          0.15.1
idna                     3.4
imageio                  2.31.1
importlib-resources      6.0.1
Jinja2                   3.1.2
joblib                   1.3.2
kiwisolver               1.4.4
langcodes                3.3.0
lit                      16.0.6
MarkupSafe               2.1.3
matplotlib               3.7.2
mkl-fft                  1.3.6
mkl-random               1.2.2
mkl-service              2.4.0
mpmath                   1.3.0
murmurhash               1.0.9
networkx                 2.2
numpy                    1.21.0
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
opencv-python            4.7.0.72
packaging                23.1
pandas                   2.0.3
pathtools                0.1.2
pathy                    0.10.2
peft                     0.4.0
Pillow                   9.3.0
pip                      23.1.2
plyfile                  0.9
pointnet2                0.0.0
preshed                  3.0.8
protobuf                 4.24.0
psutil                   5.9.5
pydantic                 2.1.1
pydantic_core            2.4.0
pyparsing                3.0.9
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
regex                    2023.6.3
requests                 2.31.0
safetensors              0.3.1
scikit-learn             1.3.0
scipy                    1.10.1
sentry-sdk               1.29.2
setproctitle             1.3.2
setuptools               67.8.0
six                      1.16.0
smart-open               6.3.0
smmap                    5.0.0
spacy                    3.6.1
spacy-legacy             3.0.12
spacy-loggers            1.0.4
srsly                    2.4.7
sympy                    1.12
tensorboardX             2.6.2
thinc                    8.1.11
threadpoolctl            3.2.0
tokenizers               0.13.3
torch                    1.7.1+cu110
torchaudio               0.7.2
torchvision              0.8.2+cu110
tqdm                     4.65.0
transformers             4.30.2
trimesh                  2.35.39
triton                   2.0.0
typer                    0.9.0
typing_extensions        4.6.3
tzdata                   2023.3
urllib3                  2.0.3
wandb                    0.15.8
wasabi                   1.1.2
wheel                    0.38.4
zipp                     3.16.2
```

**Comment by 1301358882** [comment]
![1712139689456](https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/139096668/95c2dc00-46c0-4107-a904-cd2a216909f1)
![1712144309647](https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/139096668/1eefef2f-9b42-43a3-9175-2c501de8de24)
could you tell me how to solve this situation？

**Comment by ch3cook-fdu** [comment]
Maybe you could try installing the desired `gcc>8.0, g++>8.0` packages.

**Comment by 1301358882** [comment]
running install
/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing pointnet2.egg-info/PKG-INFO
writing dependency_links to pointnet2.egg-info/dependency_links.txt
writing top-level names to pointnet2.egg-info/top_level.txt
reading manifest file 'pointnet2.egg-info/SOURCES.txt'
writing manifest file 'pointnet2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'pointnet2._ext' extension
Emitting ninja build file /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/4] /usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/group_points_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/group_points_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
FAILED: /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/group_points_gpu.o 
/usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/group_points_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/group_points_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
In file included from /usr/local/cuda-10.1/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.1/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
[2/4] /usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/ball_query_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/ball_query_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
FAILED: /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/ball_query_gpu.o 
/usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/ball_query_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/ball_query_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
In file included from /usr/local/cuda-10.1/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.1/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
[3/4] /usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/sampling_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/sampling_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
FAILED: /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/sampling_gpu.o 
/usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/sampling_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/sampling_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
In file included from /usr/local/cuda-10.1/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.1/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
[4/4] /usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/interpolate_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/interpolate_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
FAILED: /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/interpolate_gpu.o 
/usr/local/cuda-10.1/bin/nvcc -I/home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/TH -I/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/mi/anaconda3/envs/vote/include/python3.8 -c -c /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/_ext_src/src/interpolate_gpu.cu -o /home/mi/Student_file/WY/Vote2Cap-DETR-master/third_party/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/interpolate_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -ccbin /home/mi/anaconda3/bin/x86_64-conda-linux-gnu-cc -std=c++14
In file included from /usr/local/cuda-10.1/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.1/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/command/install.py", line 87, in run
    self.do_egg_install()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/command/install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/mi/anaconda3/envs/vote/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
![1712459504788](https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/139096668/db43ca51-a06b-4433-97b1-435f97002291)

I have changed the gcc version to 8.4.0 and this error still occurs.

**Comment by 1301358882** [comment]
> Maybe you could try installing the desired `gcc>8.0, g++>8.0` packages.

Could you see how to solve such an error? Thank you very much!

**Comment by ch3cook-fdu** [comment]
That‘s how I deal with the pointnet2 package:

1. Re-installing the cuda driver:
```
wget https://developer.download.nvidia.com/compute/cuda/11.1.0/local_installers/cuda_11.1.0_455.23.05_linux.run
sudo sh cuda_11.1.0_455.23.05_linux.run
```

2. Re-install the torch packages.
3. Build pointnet2 via `python setup.py install`

Hope this will help.

**Comment by 1301358882** [comment]
> ```
> sudo sh cuda_11.1.0_455.23.05_linux.run
> ```

Thank you very much for your answer. The previous problem has been solved, but now there is a new problem, and the following error occurs during the train process (ubuntu18.04 + Tesla P100 + cuda 11.0 + pytorch 1.7.1 + python 3.8.13).
![1712805131686](https://github.com/ch3cook-fdu/Vote2Cap-DETR/assets/139096668/e2180382-8cc4-4d6b-9f11-107d69f6b4e1)

**Comment by ch3cook-fdu** [comment]
Please try delete all the compiled files and re-compile the pointnet2. There might be some cached files that might cause this error.
